### ISSUE TITLE
Time Warp is half off the screen

### ISSUE THREAD

**Issue by armarayo** [lisa-lionheart/TimeWarp#1]
Time Warp is half off the screen.
Cannot control sliders.

https://www.reddit.com/r/CitiesSkylines/comments/3m71rj/steam_guide_mod_compatibility_guide_for_after_dark/cvdwh5k

https://imgur.com/a/gaPXp

**Comment by armarayo** [comment]
Hey Lisa,

I was wondering if your going to address this issue anytime soon? I really want to use Time Warp but cannot because the panel is half off screen so I can't use it :/ Can you fix it's position or make it drag-able?

Thank you for your concern :)

**Comment by lisa-lionheart** [comment]
Yeah it will get done this week, I really didn't want to do any coding this weekend as I was a little overwhelmed but I will fix it this week promise

**Comment by armarayo** [comment]
Thank you for answering :) I'm hoping to use Time Warp anytime soon - Even more than Traffic report - which I love too. One of the best mods.
